---
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:stable_freqairl
    # # Enable GPU Image and GPU Resources
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: Dockerfile
      args:
        optuna_version: 4.7.0
    restart: unless-stopped
    container_name: freqtrade-ReforceXY
    environment:
      - TZ=Europe/Sofia
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8082
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "0.0.0.0:8082:8080"
    # Default command used when running `docker compose up`
    command: trade
